### PR TITLE
Add support for bulk 2.0

### PR DESCRIPTION
**Pull request by zhiweio**
This PR adds support for Bulk API 2.0, which is a feature of Salesforce that allows users to perform large-scale data operations.
This PR will benefit users who need to use Bulk API 2.0 for their data needs.

ref: [Bulk API 2.0 and Bulk API Developer Guide](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/)

### CODE REVIEW

**Comment by zhiweio** [comment]
Hi, @jon-wobken, I appreciate your efforts. Could you please review this PR, thank you

**Comment by drbjim** [comment]
@zhiweio you can take https://github.com/simple-salesforce/simple-salesforce/issues/299 if you want

**Comment by zhiweio** [comment]
> @zhiweio you can take #299 if you want

I'd be happy to take it, how can I be assigned for this issue? I'm new on github contribution

**Review by jon-wobken — APPROVED** [review]

**Comment by alaminopu** [comment]
@zhiweio bulk 2.0 missing `query_all` operation. Was it intentional?

**Pull request merged**
