### PR TITLE
Add typing annotations

### LINKED ISSUE #659: Add typing annotations
Hi, I wanted to use this awesome library today, but I found out that you are not using any type annotations. 
Is there a reason for this?
I find it more convenient since type annotations kinda "document the code" and help newcomers to use it. It's also nice to get autocomplete in IDEs like PyCharm etc. and could help to find possible type issues.
I would offer to create a PR to add some.

### PR DESCRIPTION
**Pull request by Shadow-Devil**
Closes #659

Adds type annotations to all functions (except tests). 
Also adds mypy type checking to the tox testenv:static command.
Unfortunately, there are still some `Any`s inside the codebase.

### CODE REVIEW

**Comment by syphar** [comment]
Thank you for this huge undertaking! 

I can help reviewing this when I'm back from my trip, two general points: 

- [when then the package is fully typed, we should add a `py.typed` file](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages)
- at a first glance, there are some `Any` too many, especially in `Dict[str, Any]` when we actually don't want to allow other `Dict` or `List` values, or generic `Any` return values in some places. Though we could argue that we keep it simple for now, and improve later on this.

**Comment by Shadow-Devil** [comment]
Since I don't know this library that well I added `Any` where I was not sure if there was any type restriction or not. Feel free to suggest more improvements and I'm happy to include them in this PR as well :)

**Comment by Shadow-Devil** [comment]
I can also revert some of the newer commits, they are kinda "fancy additions", that might not be welcomed. Just let me know...

**Comment by Shadow-Devil** [comment]
Hi @jon-wobken, I noticed that you are currently preparing the release of v1.12.6. 
I would highly appreciate it if this PR could also be part of this release.
I also updated the branch and fully type annotated the newish Bulk v2 API.
Thank you in advance!

**Comment by Shadow-Devil** [comment]
That sounds great 🎉 
Is it fine to switch to pytest instead of setup.py test, since it is deprecated? 
Source: https://github.com/pytest-dev/pytest/issues/5534

**Comment by Shadow-Devil** [comment]
Do you know why the Travis CI steps are run in sequence and not in parallel? This causes the pipeline to be relatively slow. Would you also consider switching to GitHub Actions?

**Pull request merged**
