### PR TITLE
Add support for querying deleted records.

### PR DESCRIPTION
**Pull request by digitalaun**
Recreating work from #152 per conversation with @andscoop .

### CODE REVIEW

**Comment by andscoop** [comment]
Thanks @digitalaun I will be taking a look and getting this merged shortly. Once again, thanks for being patient and helping out with this one!

**Comment by andscoop** [comment]
@digitalaun #225 has been merged. Can you rebase these changes onto master? At which point we'll get this merged in.

**Comment by digitalaun** [comment]
@andscoop Thanks! The changes have been rebased onto master.

**Comment by andscoop** [comment]
@digitalaun Thanks again for the work on this.

**Comment by digitalaun** [comment]
@andscoop looks like this was closed without merging. Are you planning to merge the branch locally?

**Comment by andscoop** [comment]
Misclick. This PR is now failing due to a stale test I merged just before this merge. I am going to go ahead and merge this and fix this stale test ASAP.

**Pull request merged**
