### PR TITLE
Sphinx

### PR DESCRIPTION
**Pull request by jasonschroeder-sfdc**
- most of this is auto-generated from `sphinx-quickstart`
- the contents of `user_guide` are split up from `readme.rst`

### CODE REVIEW

**Comment by jasonschroeder-sfdc** [comment]
@demianbrecht Spinx documentation. I wasn't able to assign a Github reviewer or assignee - maybe a permissions thing?

I started setup at readthedocs.org but was unable to setup a webhook from github to readthedocs. Again, not enough github permissions. Sign up for an account at readthedocs.org and I'll add you to simple-salesforce.readthedocs.org .

**Comment by nickcatal** [comment]
@jasonschroeder-sfdc you should have the necessary level of access to the repo to add RTD.

can you add `nickcatal` to manage the RTD?

Thanks

**Comment by jasonschroeder-sfdc** [comment]
@nickcatal - Added you to RTD. Please confirm.

Webhook still failing:

> Webhook activation failed. Make sure you have permissions to set it.

Can you give it a try? Just hit this: https://readthedocs.org/dashboard/simple-salesforce/resync_webhook/

**Comment by nickcatal** [comment]
@jasonschroeder-sfdc I now have access and I enabled the webhook. Thanks

**Pull request merged**
