### PR TITLE
Added support for all metadata api operations

### PR DESCRIPTION
**Pull request by pranav-dahiya**
Had to add a dependency for zeep to perform SOAP api calls.

### CODE REVIEW

**Comment by pranav-dahiya** [comment]
I have left deploy and retrieve as they were so that there are no conflicts with existing code. These can also be changed to use zeep to make it simpler in the future.

**Comment by pranav-dahiya** [comment]
Now this supports similar syntax to bulk operations. Example:
```Python
sf = Salesforce('username', 'password', 'token')
mdapi = sf.mdapi
new_object = mdapi.CustomObject.new(
    fullName='APITest__c',
    label='API Test Object',
    pluralLabel='API Test Objects',
    deploymentStatus=mdapi.DeploymentStatus.new('Deployed'),
    sharingModel=mdapi.SharingModel.new('ReadWrite'),
    nameField=mdapi.CustomField.new(label='API Test Object name', type=mdapi.FieldType.new('Text')
)
mdapi.CustomObject.create([new_object])
print(mdapi.CustomObject.read(['APITest__c'])[0])
```

**Comment by pranav-dahiya** [comment]
Now new() method has been replaced with __call__. So above example works as:
```Python
sf = Salesforce('username', 'password', 'token')
mdapi = sf.mdapi
new_object = mdapi.CustomObject(
    fullName='APITest__c',
    label='API Test Object',
    pluralLabel='API Test Objects',
    deploymentStatus=mdapi.DeploymentStatus('Deployed'),
    sharingModel=mdapi.SharingModel('ReadWrite'),
    nameField=mdapi.CustomField(label='API Test Object name', type=mdapi.FieldType('Text')
)
mdapi.CustomObject.create([new_object])
print(mdapi.CustomObject.read(['APITest__c'])[0])
```
Also fixed an issue with readMetadata calls where CustomTypes in the response from Salesforce were not being parsed successfully.

**Comment by jon-wobken** [comment]
@pranav-dahiya - I like this a lot just going to need some time to review over these next few days. If you could include some information in the read-me that would be fantastic.

**Comment by pranav-dahiya** [comment]
@jon-wobken Sure. I can do that. I would also like to make some changes to this before you merge it. I did not realize this earlier, but since eventually lists are converted to multiple occurrences of the same tag in request XML, the parameters to these methods don't necessarily need to be lists if you only want to deal with a single component. This can be documented in the docstrings, and the return value can also be changed to a single object instead of a list of length 1, for single input. Its just a small quality of life improvement

**Comment by pranav-dahiya** [comment]
@jon-wobken I have added a new section to the readme

**Comment by jon-wobken** [comment]
@pranav-dahiya - Looks like there are some failed tests. I'll look to check/update these on my off day (Friday) and then integrate this pull. Appreciate the readme!

**Comment by AlexanderVR** [comment]
I tried installing this fork locally. Needed `include simple_salesforce/metadata.wsdl`  added to MANIFEST.in to get things working.

**Pull request merged**
