### PR TITLE
Fix: Use `client_credentials` grant type when consumer_key and consumer_secret are passed

### LINKED ISSUE #753: OAuth2 Client Credentials workflow grant type is incorrect
## Problem Statement

When I run this code:

```python
    @property
    def salesforce_connection(self) -> Salesforce:
        if not hasattr(self, "_salesforce_connection"):
            self._salesforce_connection = Salesforce(
                username=self.args.salesforce_username,
                password=self.args.salesforce_password,
                consumer_key=self.args.salesforce_consumer_key,
                consumer_secret=self.args.salesforce_consumer_secret,
            )
        return self._salesforce_connection
```

I receive this error:

```
  File "/path/to/python/lib/python3.12/site-packages/simple_salesforce/login.py", line 310, in token_login
    raise SalesforceAuthenticationFailed(except_code, except_msg)
simple_salesforce.exceptions.SalesforceAuthenticationFailed: invalid_grant: authentication failure
```

## Versions

- `simple_salesforce==1.12.6`
- Salesforce API version `59`
- Python 3.12

## Analysis

When this package issues a token request using the client credentials workflow, it sets the `grant_type` to `password`.

https://github.com/simple-salesforce/simple-salesforce/blob/1d28fa18438d3840140900d4c00799798bad57b8/simple_salesforce/login.py#L116-L121

According to the [salesforce docs](https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_client_credentials_flow.htm&type=5) the only correct value for `grant_type` is **`client_credentials`**.  Which is why the error message says "invalid grant". Because `password` is not a valid grant for this OAuth flow. 

If I manually override this value to, the exception is avoided and my script runs as expected. 

I am opening a pull request which implements a fix for this.

### PR DESCRIPTION
**Pull request by susodapop**
## Description

This pull request is a one-line change to `login.py`. It updates the grant type when a `consumer_key` and `consumer_secret` are passed into `Salesforce()`. Without this change, client credentials flows fail due to an `invalid_grant` error.

I have run the test suite locally. Although I'll note that the connected apps tests passed both before _and_ after this change. Likely because of how it uses mocks rather than connecting to a real salesforce instance. If you'd like me to add an e2e test for this behavior, please let me know. 

## Related Tickets & Documents

Closes #753
[Salesforce docs about grant types for client credentials workflow](https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_client_credentials_flow.htm&type=5)

### CODE REVIEW

**Comment by williambritt** [comment]
Would this cause a breaking change for any existing implementations using the grant type of `password`?

https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_username_password_flow.htm&type=5

**Comment by susodapop** [comment]
Not at all. My change is gated behind an if-condition which already exists in the latest release:

https://github.com/simple-salesforce/simple-salesforce/blob/8a0e1ea5af23c7a36444c3862f0042914f46f42a/simple_salesforce/login.py#L116-L119

Whereas the password grant is handled when:

https://github.com/simple-salesforce/simple-salesforce/blob/8a0e1ea5af23c7a36444c3862f0042914f46f42a/simple_salesforce/login.py#L155

Anyone calling simple salesforce in this way today would already see an exception, since the `client_credentials` is the _only_ allowed grant_type with this kind of request.

**Comment by syphar** [comment]
> Would this cause a breaking change for any existing implementations using the grant type of `password`?
> 
> https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_username_password_flow.htm&type=5

From what I see, this would be a breaking change. 

Right now I can login via user, password, client-key & secret and the given user would be used. 

After the change, with the same parameters, the given user would be ignored (as I understand the client credentials flow). 

I think the normal client-credentials flow is already covered: 
https://github.com/simple-salesforce/simple-salesforce/blob/1d28fa18438d3840140900d4c00799798bad57b8/simple_salesforce/login.py#L200-L202

and it works when given just `consumer_key`, `consumer_secret`, and the correct org subdomain (not `login` or `test).

**Comment by syphar** [comment]
Also looking at the SF docs in the PR description, the existing client credentails flow is exactly what the documentation describes, I don't see why we need this PR

**Comment by susodapop** [comment]
Thank you @syphar I believe you are correct! I'm closing this PR, as I had I missed that line 202 where the `client_credentials` grant is used.

**Pull request closed without merging**
