### PR TITLE
Fix unicode handling in SalesforceError

### PR DESCRIPTION
**Pull request by Daenyth**
I confirmed with tox that the test fails without the change to util.py and passes with it.

### CODE REVIEW

**Comment by Daenyth** [comment]
I also recommend using the [`future`](http://python-future.org/index.html) library for compatibility with python2+3 - it's a huge time saver and has a [convenient decorator](http://python-future.org/compatible_idioms.html#custom-str-methods) for this case.

**Comment by Daenyth** [comment]
`tox -e static` passes locally for me - anyone know what's up with that?

**Comment by Daenyth** [comment]
cc @demianbrecht

**Comment by demianbrecht** [comment]
@Daenyth do you have global pylint config that may be overriding the local one?

**Comment by Daenyth** [comment]
Not that I'm aware of. Shouldn't the `tox` build be taking care of that anyway?

**Comment by demianbrecht** [comment]
Yeah, it should be. I'll try to take a look at what's going on today. Thanks!

**Comment by Daenyth** [comment]
I probably won't be coming back to this as I'm not working in python at the moment - anyone else feel free to take up this branch and take it the rest of the way

**Pull request closed without merging**
