### PR TITLE
Handle 204 in set password

### PR DESCRIPTION
**Pull request by fameoflight**
@nickcatal

### CODE REVIEW

**Comment by nickcatal** [comment]
@fameoflight can you explain what issue this PR is fixing?

**Comment by fameoflight** [comment]
Handling 204 correctly. 

204 means no response so don't try to read the content if the status type is 204.

**Comment by nickcatal** [comment]
Got it.

To be consistent with how `.delete()` works, can you have it return the status code of the request instead of `None`?

Then I can merge this in

**Comment by andscoop** [comment]
@nickcatal Should we push for code consolidation? Directly above this change we are already checking for `status_code != 204`.

@fameoflight Is there any advantage to doing a check for a 204 and returning None vs just checking the JSON body and returning None if len is zero?

**Comment by andscoop** [comment]
Looking at docs in code comment, I think we should throw an error `status_code != 204` and `return None` `if status_code == 204`. That would be an easy fix for now.

In the long term it would be nice to see all `status_code` logic moved into it's own method off of `_call_salesforce` similar to how we handle >=300 errors now.

I do not believe this code get's us close enough to a final solution to warrant a merge.

**Pull request closed without merging**
