### PR TITLE
Updated requests dependency to requests[security]

### PR DESCRIPTION
**Pull request by demianbrecht**
Addresses issue #103

### CODE REVIEW

**Comment by demianbrecht** [comment]
FYI @nickcatal

**Comment by nickcatal** [comment]
Can you update the version in setup.py so we can send to pypi?

**Comment by nickcatal** [comment]
Q2: Would it make sense to use `pyver_install_requires` so that people on newer python aren't required to download a new version of requests from what they may already have installed either in their existing simple-salesforce environment or system-wide?

I'm inclined to think that makes more sense. Especially since we do test against older versions of python.

Thoughts?

**Comment by demianbrecht** [comment]
> Can you update the version in setup.py so we can send to pypi?

Yep, will do.

> Would it make sense to use pyver_install_requires so that people on newer python aren't required to download a new version of requests from what they may already have installed either in their existing simple-salesforce environment or system-wide?

I was considering that. My thinking here was that, because openssl releases more frequently than python, it would likely be best from a security perspective to allow for system openssl use across the board instead of only < 2.7.9.

That said, it can also have adverse effects should the user's system openssl be older than Python's (hopefully never the case, but I'm sure it's bound to happen). Perhaps a disclaimer in the README about ensuring an up to date system openssl would be the best way to mitigate any backwards incompatibility issues that crop up due to the change?

**Comment by nickcatal** [comment]
@demianbrecht it looks like [2.6](https://travis-ci.org/simple-salesforce/simple-salesforce/jobs/136519654), [2.7](https://travis-ci.org/simple-salesforce/simple-salesforce/jobs/136519656), and pypi are failing tests with this due to handshake issues.

I wasn't aware we were doing actual calls to salesforce as part of tests, but any idea what might be going on here? I can't think of anything off the top of my head.

**Comment by demianbrecht** [comment]
It's an issue with httpretty (it's in the callstack). The issue in their issue tracker: https://github.com/gabrielfalcao/HTTPretty/issues/242. I've run into problems with httpretty before, so it might be worthwhile to just swap it out for responses (https://github.com/getsentry/responses). I'm gonna give that a go.

**Comment by demianbrecht** [comment]
All tests are passing, @nickcatal when you get a chance, I'll merge this after a 👍

**Comment by nickcatal** [comment]
Looks good to me!

**Pull request merged**
