### PR TITLE
adding support for retreiving multiple batches in query operation

### PR DESCRIPTION
**Pull request by skamensky**
A small fix for issue https://github.com/simple-salesforce/simple-salesforce/issues/280

### CODE REVIEW

**Comment by gglanzani** [comment]
We would really like for this to get through as well. Is there anything blocking it? The code change proposed seems fairly simple (although I would have liked a list comprehension more, but that would require an extra helper function to make it clean/clear).

**Comment by skamensky** [comment]
@gglanzani , yes the thing blocking this is issue https://github.com/simple-salesforce/simple-salesforce/issues/282. Additionally, if you'd like to add list comprehension, feel free to fork my repo!

**Comment by gglanzani** [comment]
@skamensky No need! Thanks for spotting this and fixing it!

**Comment by skamensky** [comment]
@andscoop Thanks for the pylint fix. I've rebased and pushed my changes on top of your commits. Travis is content! Can this be merged?

**Comment by andscoop** [comment]
@skamensky I am definitely willing to merge, would you have any interest in adding a test for this use case? We'd like to increase coverage.

**Comment by skamensky** [comment]
@andscoop 
Yes that's a good idea! I'll need to look at how you guys are doing testing. I'll look at it this weekend. I may have some questions. Once I understand it I'll probably add a `README.rst` to help make creating tests easier for contributors.

Any one liner tips or gotchas before I check it out this weekend?

**Comment by andscoop** [comment]
@skamensky Awesome, thanks for agreeing to try it out!

The docs are fairly decent (but always welcoming improvement). Only piece of advice is to read up on mocking if you haven't written tests before. You should be able to extend (or make a small change) to an existing test.

Let me know if any challenges arise.

**Comment by wyattshapiro** [comment]
@andscoop @skamensky 
Does this still Need Tests? Willing to give it a go if so.

**Comment by skamensky** [comment]
@wyattshapiro , yes it needs tests which is why this was never merged. I didn't write them because at the time I didn't know how and these days I don't use Salesforce anymore.

**Comment by wyattshapiro** [comment]
@skamensky thanks for the update

It actually looks like someone has a PR for this issue that does have a unit test so I will see what is stopping the merge there:
https://github.com/simple-salesforce/simple-salesforce/pull/323

**Comment by jon-wobken** [comment]
Added support in #392

**Pull request closed without merging**
